name: "Beszel-Agent"
description: "Beszel-Agent for Home Assistant"
url: "https://github.com/RichardD012/homeassistant-beszel-agent"
version: "0.10.2"
slug: "updated-beszel-agent"
init: false
stdin: true
hassio_api: false
homeassistant_api: false
docker_api: true
host_network: true
options:
  public_key: null
schema:
  public_key: str
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
image: "richardd012/homeassistant-beszel-agent-{arch}"
