name: "Beszel-Agent"
description: "Beszel-Agent for Home Assistant"
url: "https://github.com/matthewhadley/homeassistant-beszel-agent"
version: "0.3.0"
slug: "beszel-agent"
init: false
stdin: true
hassio_api: false
homeassistant_api: false
docker_api: true
options:
  public_key: null
schema:
  public_key: str
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
image: "matthewhadley/homeassistant-beszel-agent-{arch}"
